Lab01/Lab01GUI/Controllers/RC5EncryptionController.cs
using Lab01GUI.Services.Implementation;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab01GUI.Controllers;

[RequestSizeLimit(2_000_000_000)]
[RequestFormLimits(MultipartBodyLengthLimit = 2_000_000_000)]
public class RC5EncryptionController : Controller
{
	private readonly RC5_CBC_PadService _rc5Service = new(
		new RC5_CBC_PadService.WordLength(16), // WordLength
		12, // Number of Rounds
		16 // Secret Key Length in Bytes
		);

	[HttpGet]
	public IActionResult Encrypt()
	{
		return View();
	}

	[HttpPost]
	public async Task<IActionResult> Upload(IFormFile file, string password)
	{
		if (file == null || file.Length == 0)
		{
			return BadRequest("No file uploaded.");
		}

		using var memoryStream = new MemoryStream();

		await file.CopyToAsync(memoryStream);
		var fileBytes = memoryStream.ToArray();

		var encryptedFileName = Path.GetFileNameWithoutExtension(file.FileName) + ".enc";

		Stopwatch stopwatch = new();
		stopwatch.Start();

		var encryptedBytes = _rc5Service.Encrypt(fileBytes, password);

		string tempFilePath = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid()}.enc");
		await System.IO.File.WriteAllBytesAsync(tempFilePath, encryptedBytes);

		stopwatch.Stop();
		TempData["EncryptedFilePath"] = tempFilePath;
		TempData["EncryptedFileName"] = Path.GetFileNameWithoutExtension(file.FileName) + ".enc";
		TempData["ExecutionTime"] = (int)stopwatch.ElapsedMilliseconds;
		TempData["InputLength"] = (int)file.Length;

		return RedirectToAction("ShowEncryptionResult");
	}

	[HttpGet]
	public IActionResult Decrypt()
	{
		return View();
	}

	[HttpPost]
	public async Task<IActionResult> Decrypt(IFormFile file, string password)
	{
		if (file == null || file.Length == 0)
		{
			return BadRequest("No file uploaded.");
		}

		using var memoryStream = new MemoryStream();

		await file.CopyToAsync(memoryStream);
		var fileBytes = memoryStream.ToArray();

		Stopwatch stopwatch = new();
		stopwatch.Start();

		var decryptedBytes = _rc5Service.Decrypt(fileBytes, password);

		stopwatch.Stop();

		string tempFilePath = Path.Combine(Path.GetTempPath(), $"{Guid.NewGuid()}.dec");
		await System.IO.File.WriteAllBytesAsync(tempFilePath, decryptedBytes);

		TempData["DecryptedFilePath"] = tempFilePath;
		TempData["DecryptedFileName"] = Path.GetFileNameWithoutExtension(file.FileName) + ".dec";
		TempData["ExecutionTime"] = (int)stopwatch.ElapsedMilliseconds;
		TempData["InputLength"] = (int)file.Length;

		return RedirectToAction("ShowDecryptionResult");
	}

	[HttpGet]
	public IActionResult ShowDecryptionResult()
	{
		// Retrieve decryption time and input length from TempData
		ViewBag.ExecutionTime = TempData["ExecutionTime"];
		ViewBag.InputLength = TempData["InputLength"];

		return View("Decrypt");
	}

	
	[HttpGet]
	public IActionResult ShowEncryptionResult()
	{
		// Retrieve decryption time and input length from TempData
		ViewBag.ExecutionTime = TempData["ExecutionTime"];
		ViewBag.InputLength = TempData["InputLength"];

		return View("Encrypt");
	}

	[HttpGet]
	public IActionResult DownloadEncryptedFile()
	{
		if (TempData["EncryptedFilePath"] is not string filePath || !System.IO.File.Exists(filePath))
		{
			return NoContent(); // No file available for download
		}

		var fileName = TempData["EncryptedFileName"] as string ?? "encrypted-file.enc";

		// Read the file from disk and return it as a download
		var fileBytes = System.IO.File.ReadAllBytes(filePath);

		// Delete the file after it's downloaded
		System.IO.File.Delete(filePath);

		return File(fileBytes, "application/octet-stream", fileName);
	}

	[HttpGet]
	public IActionResult DownloadDecryptedFile()
	{
		if (TempData["DecryptedFilePath"] is not string filePath || !System.IO.File.Exists(filePath))
		{
			return NoContent(); // No file available for download
		}

		var fileName = TempData["DecryptedFileName"] as string ?? "decrypted-file.dec";

		// Read the file from disk and return it as a download
		var fileBytes = System.IO.File.ReadAllBytes(filePath);

		// Delete the file after it's downloaded
		System.IO.File.Delete(filePath);

		return File(fileBytes, "application/octet-stream", fileName);
	}
}

Lab01/Lab01GUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Data Security</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab01GUI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/MD5/MD5.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Data Security</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RandomNumber" asp-action="Index">Lab 01</a>
                        </li>
                        
                        <li class="nav-item">
	                        <a class="nav-link text-dark" asp-area="" asp-controller="MD5" asp-action="Index">Lab 02</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RC5Encryption" asp-action="Encrypt">Lab 03</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RSAEncryption" asp-action="GenerateKeys">Lab 04</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DSS" asp-action="GenerateKeys">Lab 05</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="display: contents !important;">
            &copy; 2024 - Data Security <a style="display:contents !important;" asp-area="" asp-controller="RandomNumber" asp-action="Index">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>